### ISSUE TITLE
How to change in memory data to mongodb data

### ISSUE THREAD

**Issue by ngohungphuc** [diogodamiani/IdentityServer4.MongoDB#13]
How can I query to db to check user credential in mongo database. I dont want to use in memory client to test.

**Comment by diogodamiani** [comment]
Hi,

It's not responsibility of IdentityServer to deal with user management. You can use [ASP.NET Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity) to do this and [customize it's stores](https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity) to use MongoDB.

To integrate IS4 with ASP.NET Core Identity you can use [this](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity) library.
