### ISSUE TITLE
Push new nuget package

### ISSUE THREAD

**Issue by HBTeun** [diogodamiani/IdentityServer4.MongoDB#19]
Dear @diogodamiani 

Could you please push the newest version from Git to Nuget?
The latest version on nuget is from 2017

Kind regards,
Teun

**Comment by hbs-developers** [comment]
*Bump - need this as well.

**Comment by diogodamiani** [comment]
Hello guys! 
Sorry for the delay. 
I'm doing some PR validations this week and after that I'll update the package.

**Comment by diogodamiani** [comment]
New version available on Nuget.
