### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by findinfinite** [diogodamiani/IdentityServer4.MongoDB#23]
How do you use this library exactly? Are there any examples?

**Comment by Rainy99** [comment]
You can see my example with here:
https://github.com/Rainy99/IdentityServer

**Comment by findinfinite** [comment]
Can you use this to implement the ResourceOwnerPasswordValidator?

See here: https://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core

**Comment by Rainy99** [comment]
> Can you use this to implement the ResourceOwnerPasswordValidator?
> 
> See here: https://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core

I have implemented IResourceOwnerPasswordValidator and IProfileService in my example, you can see.

**Comment by findinfinite** [comment]
> > Can you use this to implement the ResourceOwnerPasswordValidator?
> > See here: https://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core
> 
> I have implemented IResourceOwnerPasswordValidator and IProfileService in my example, you can see.

I did a search for IResourceOwnerPasswordValidator  and didn't find anything.

**Comment by findinfinite** [comment]
can this be used to implement

**Comment by findinfinite** [comment]
> > > Can you use this to implement the ResourceOwnerPasswordValidator?
> > > See here: https://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core
> > 
> > 
> > I have implemented IResourceOwnerPasswordValidator and IProfileService in my example, you can see.
> 
> I did a search for IResourceOwnerPasswordValidator and didn't find anything.

Actually, I didn't realize you pushed recently so I did a git pull and found it. Great work! :) And thanks for the help!

**Comment by Rainy99** [comment]
> > > > Can you use this to implement the ResourceOwnerPasswordValidator?
> > > > See here: https://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core
> > > 
> > > 
> > > I have implemented IResourceOwnerPasswordValidator and IProfileService in my example, you can see.
> > 
> > 
> > I did a search for IResourceOwnerPasswordValidator and didn't find anything.
> 
> Actually, I didn't realize you pushed recently so I did a git pull and found it. Great work! :) And thanks for the help!

You are welcome.

**Comment by diogodamiani** [comment]
@findinfinite The purpose of this library is provide a configuration and operational persistence layer using MongoDB for IS4. The user validation is up to your application. 

The sample app [here](https://github.com/diogodamiani/IdentityServer4.Contrib.MongoDB/tree/dev/src/Host) don't use it.

@Rainy99 Thank you for your help.
