### ISSUE TITLE
IApplicationLifetime is obsolete in .Net Core 3

### ISSUE THREAD

**Issue by audriuiv** [diogodamiani/IdentityServer4.MongoDB#24]
I want to use this package for operational data in IdentityServer 4 (.Net Core 3).
 But I get warning about applicationLifetime. It is obsolete.
`app.UseIdentityServerMongoDBTokenCleanup(applicationLifetime);`
More info: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.iapplicationlifetime?view=dotnet-plat-ext-3.0&viewFallbackFrom=aspnetcore-2.1
Can you help me?

**Comment by tbureck** [comment]
This is fixed as of [this commit](https://github.com/diogodamiani/IdentityServer4.Contrib.MongoDB/commit/102a30e2512f91249ddd79949a7674c1226db375) and will be in the next release. In the meantime you can keep using the current version which will still work with .NET Core 3 or [update to 4.0.0-rc.1](https://www.nuget.org/packages/IdentityServer4.Contrib.MongoDB/4.0.0-rc.1).
