### ISSUE TITLE
Method 'FindIdentityResourcesByScopeNameAsync' no implemented

### ISSUE THREAD

**Issue by andmaltes** [diogodamiani/IdentityServer4.MongoDB#33]
HI, i am facing this error and I have no idea how to check this :(

System.TypeLoadException: 'Method 'FindIdentityResourcesByScopeNameAsync' in type 'IdentityServer4.MongoDB.Stores.ResourceStore' from assembly 'IdentityServer4.Contrib.MongoDB, Version=2.3.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

The code:

 _ = services.AddIdentityServer().AddDeveloperSigningCredential()
       // this adds the operational data from DB (codes, tokens, consents)
       .AddConfigurationStore(options =>
       {
           
           options.ConnectionString = "mongodb://localhost/myDB";
       })
    .AddOperationalStore(options =>
    {
        
        options.ConnectionString = "mongodb://localhost/myDB";
    })
   .AddInMemoryIdentityResources(Config.GetIdentityResources())
   .AddInMemoryApiResources(Config.GetApiResources())
   .AddInMemoryClients(Config.GetClients())
   .AddAspNetIdentity<ApplicationUser>();

<PackageReference Include="AspNetCore.Identity.Mongo" Version="6.7.2" />
    <PackageReference Include="IdentityServer4" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.Contrib.MongoDB" Version="2.3.4" />
    <PackageReference Include="IdentityServer4.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.7" />
Thanks

**Comment by andmaltes** [comment]
<PackageReference Include="AspNetCore.Identity.Mongo" Version="6.7.2" />
    <PackageReference Include="IdentityServer4" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.Contrib.MongoDB" Version="2.3.4" />
    <PackageReference Include="IdentityServer4.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.7" />

**Comment by andmaltes** [comment]
<PackageReference Include="AspNetCore.Identity.Mongo" Version="6.7.2" />
    <PackageReference Include="IdentityServer4" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.0.4" />
    <PackageReference Include="IdentityServer4.Contrib.MongoDB" Version="2.3.4" />
    <PackageReference Include="IdentityServer4.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.7" />

**Comment by andmaltes** [comment]
PackageReference Include="AspNetCore.Identity.Mongo" Version="6.7.2"
PackageReference Include="IdentityServer4" Version="4.0.4"
PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.0.4"
PackageReference Include="IdentityServer4.Contrib.MongoDB" Version="2.3.4"
PackageReference Include="IdentityServer4.Storage" Version="4.0.4"
PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.7"

**Comment by diogodamiani** [comment]
Hi, 

The version 2.3.4 is not compatible with IS4 4.0.x. 

Please, use the [4.0.0-RC1](https://www.nuget.org/packages/IdentityServer4.Contrib.MongoDB/4.0.0-rc.1) and pay attention to the breaking changes.

Cheers!
