### ISSUE TITLE
System.NotSupportedException exception in CorsPolicyService

### ISSUE THREAD

**Issue by Greyhouse-Consulting** [diogodamiani/IdentityServer4.MongoDB#4]
Hi, 

I'm getting and exception System.NotSupportedException in CorsPolicyService when calling the token endpoint directly from postman. This can be reproduced by starting the host project and call the token endpoint using this setup

```
POST /connect/token HTTP/1.1
Host: localhost:1941
Authorization: Basic Y2xpZW50OnNlY3JldA==
Origin: *
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: c5627d4f-41bc-4b11-d9fd-82ecc3e78ebe

grant_type=client_credentials&scope=api1
```

And the exception details

> An exception of type 'System.NotSupportedException' occurred in MongoDB.Driver.dll but was not handled in user code
> 
> Additional information: Unable to determine the serialization information for the collection selector in the tree: aggregate([]).SelectMany(x => x.AllowedCorsOrigins.Select(y => y.Origin))

**Comment by diogodamiani** [comment]
Hi, @matand! It's really a bug. It seems to be inside MongoDB driver. I'm going to release a patch. Thank you!
