### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by mshirishkumar** [diogodamiani/IdentityServer4.MongoDB#5]
Hi diogodamiani
Could you please help us in integrating user management like register page with identityserver4 and MongoDB.

Thanks

**Comment by diogodamiani** [comment]
Hi,

It's not responsibility of IdentityServer to deal with user management. You can use [ASP.NET Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity) to do this and [customize it's stores](https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity) to use MongoDB.

To integrate IS4 with ASP.NET Core Identity you can use [this](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity) library.

I hope it helps!

**Comment by mshirishkumar** [comment]
Thanks diogodamiani. It helps lot.
