### ISSUE TITLE
net461, why?

### ISSUE THREAD

**Issue by Mardoxx** [diogodamiani/IdentityServer4.MongoDB#6]
Any technical reason why this targets net461?

**Comment by diogodamiani** [comment]
That's because the following error:

> Install-Package : Could not install package 'IdentityServer4.MongoDB 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework.

I have projects targeting .NET Full that need to use. Maybe I should change it to net452, like IdentityServer4.EF.
