### ISSUE TITLE
Error connecting to http://192.168.1.111/.well-known/openid-configuration: HTTPS required

### ISSUE THREAD

**Issue by hyy829119** [diogodamiani/IdentityServer4.MongoDB#7]
Hi,How are you
After I released the code directly deployed to Centos environment, and then use the Client Demo connection, an error, required to HTTPS requests, but in the browser is HTTP and HTTPS can access this address

Error connecting to http://192.168.1.111/.well-known/openid-configuration: HTTPS required

What are the possible causes of this error?

**Comment by diogodamiani** [comment]
Hi,

It's configurable in client policies. See in the docs: http://docs.identityserver.io/en/release/endpoints/discovery.html

Regards

**Comment by jacksondaw** [comment]
Updated link to the docs: http://docs.identityserver.io/en/latest/topics/discovery.html

**Comment by Greeng0** [comment]
I actually found the relevant configurations at http://docs.identityserver.io/en/aspnetcore1/endpoints/discovery.html, perhaps an error on @jacksondaw's part

**Comment by arisliang** [comment]
There's no DiscoveryClient in IdentityServer4 I suppose? So how can it be done now?

**Comment by aruss** [comment]
As stated here https://identitymodel.readthedocs.io/en/latest/client/discovery.html you can provide a policy. This is how I do it, `appOptions.Authority` contains a URI to the identity server. 

```csharp
services.AddSingleton<IDiscoveryCache>(r =>
{
    IHttpClientFactory factory =
        r.GetRequiredService<IHttpClientFactory>();

    DiscoveryPolicy policy = new DiscoveryPolicy
    {
        RequireHttps = appOptions.Authority.StartsWith("https")
    }; 
                
    return new DiscoveryCache(
        appOptions.Authority,
        () => factory.CreateClient(),
        policy);
});
```
