### ISSUE TITLE
.NetCore 2

### ISSUE THREAD

**Issue by giovanibarili** [diogodamiani/IdentityServer4.MongoDB#9]
Hi!

Is there any update for the new version of .netcore?

**Comment by diogodamiani** [comment]
Hi, Giovani!

I'll work on that. Probably next weak.

**Comment by nickverschueren** [comment]
I forked the source, did the work and created a pull request for you.

**Comment by diogodamiani** [comment]
Thanks Nick! I'll review it.

**Comment by farshid3003** [comment]
would you please release it for 2.0

**Comment by ngohungphuc** [comment]
@farshid3003  i'm already see .net core 2.0 version

**Comment by farshid3003** [comment]
You right but nuget is not uptodate

**Comment by ngohungphuc** [comment]
@diogodamiani could you please update nuget

**Comment by vinothbellie** [comment]
@Diago - how do I test the solution? Do you have a client application along with it? 
Regards,
Vinoth

**Comment by diogodamiani** [comment]
@vinothbellie,
You can use [IdentityServer4 Sample Clients](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients).

**Comment by diogodamiani** [comment]
It's released! 
Thanks @nickverschueren for contribution and sorry about the delay. I've been really busy in the past few days!

Cheers
